env:
  browser: true
  es2021: true

plugins:
  - react
  - '@typescript-eslint'
  - unicorn
  - sonarjs
  - jsx-a11y

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - plugin:unicorn/recommended
  - plugin:sonarjs/recommended
  - plugin:jsx-a11y/recommended

overrides: []

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
  tsconfigRootDir: .

settings:
  react:
    version: detect

rules:
  indent:
    - error
    - tab

  linebreak-style:
    - error
    - unix

  quotes:
    - error
    - single

  semi:
    - error
    - always

  react/jsx-uses-react: off
  react/react-in-jsx-scope: off

  sort-imports:
    - error
    - ignoreCase: true
      ignoreDeclarationSort: true
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - multiple
        - single
      allowSeparatedGroups: false

  # These two rules do not play well with CSS modules.
  # Otherwise all of the styles throw en error :/
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-member-access': off

  '@typescript-eslint/consistent-type-imports':
    - error
    - fixStyle: inline-type-imports

  '@typescript-eslint/method-signature-style':
    - error
    - property

  '@typescript-eslint/consistent-type-exports': error
  '@typescript-eslint/explicit-function-return-type': error
  '@typescript-eslint/explicit-member-accessibility': error
  '@typescript-eslint/member-ordering': error
  '@typescript-eslint/no-confusing-void-expression': error
  '@typescript-eslint/no-redundant-type-constituents': error
  '@typescript-eslint/no-unnecessary-qualifier': error
  '@typescript-eslint/prefer-enum-initializers': error
  '@typescript-eslint/prefer-readonly': error
  '@typescript-eslint/prefer-return-this-type': error
  '@typescript-eslint/promise-function-async': error
  '@typescript-eslint/sort-type-constituents': error
  '@typescript-eslint/strict-boolean-expressions': error
  '@typescript-eslint/switch-exhaustiveness-check': error

  unicorn/filename-case: off
  unicorn/no-useless-undefined: warn
  unicorn/no-array-method-this-argument: warn
  unicorn/prefer-ternary: warn
