extends:
  - stylelint-config-standard
  - stylelint-config-clean-order

plugins:
  - stylelint-8-point-grid
  - stylelint-css-modules
  - stylelint-high-performance-animation

ignoreFiles:
  - "**/*.ts"
  - "**/*.tsx"
  - "**/*.jpg"
