extends:
  - stylelint-config-standard
  - stylelint-config-css-modules
  - stylelint-config-rational-order-fix

plugins:
  - stylelint-order
  - stylelint-config-rational-order-fix/plugin
  - stylelint-no-unsupported-browser-features
  - stylelint-high-performance-animation

rules:
  declaration-empty-line-before: null

  selector-type-case:
    - lower
    - ignoreTypes:
        - /^\\$\\w+/

  # Ordering rules
  plugin/rational-order:
    - true
    - border-in-box-model: false
      empty-line-between-groups: true
      severity: warning

  # Unsupported features rules
  plugin/no-unsupported-browser-features:
    - true
    - browsers:
        - '> 5%'
        - Last 2 versions
        - not dead
        - not op_mini all
      ignore:
        - rem
        - css3-cursors
      ignorePartialSupport: true
      severity: warning

  # Low performance animations rules
  plugin/no-low-performance-animation-properties:
    - true
    - severity: warning

ignoreFiles:
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.jpg'
